In [64]:
import numpy as np
import pandas as pd  
import matplotlib.pyplot as plt
%matplotlib inline

In [65]:
bankdata = pd.read_csv("bill_authentication.csv")  

# see the data
bankdata.shape  

# see head
bankdata.head()  

Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [66]:
X = bankdata.drop('Class', axis=1)  
y = bankdata['Class']  

In [67]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)  

In [68]:
from sklearn.svm import SVC  
svclassifier = SVC(kernel='linear')  
svclassifier.fit(X_train, y_train)  


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [69]:
y_pred = svclassifier.predict(X_test)  
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  

[[145   1]
 [  1 128]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       146
           1       0.99      0.99      0.99       129

   micro avg       0.99      0.99      0.99       275
   macro avg       0.99      0.99      0.99       275
weighted avg       0.99      0.99      0.99       275



In [70]:
# Assign colum names to the dataset
colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

# Read dataset to pandas dataframe
irisdata = pd.read_csv("iris.data", names=colnames) 

# process
X = irisdata.drop('Class', axis=1)  
y = irisdata['Class']  

# train
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state=1234)  

In [71]:
X_train

sepal-length  sepal-width  petal-length  petal-width
98            5.1          2.5           3.0          1.1
126           6.2          2.8           4.8          1.8
40            5.0          3.5           1.3          0.3
133           6.3          2.8           5.1          1.5
77            6.7          3.0           5.0          1.7
24            4.8          3.4           1.9          0.2
8             4.4          2.9           1.4          0.2
20            5.4          3.4           1.7          0.2
22            4.6          3.6           1.0          0.2
93            5.0          2.3           3.3          1.0
36            5.5          3.5           1.3          0.2
68            6.2          2.2           4.5          1.5
32            5.2          4.1           1.5          0.1
141           6.9          3.1           5.1          2.3
125           7.2          3.2           6.0          1.8
9             4.9          3.1           1.5          0.1
114           5.8          2.8           5.1          2.4
145           6.7          3.0           5.2          2.3
135           7.7          3.0           6.1          2.3
140           6.7          3.1           5.6          2.4
1             4.9          3.0           1.4          0.2
147           6.5          3.0           5.2          2.0
105           7.6          3.0           6.6          2.1
97            6.2          2.9           4.3          1.3
57            4.9          2.4           3.3          1.0
64            5.6          2.9           3.6          1.3
66            5.6          3.0           4.5          1.5
52            6.9          3.1           4.9          1.5
58            6.6          2.9           4.6          1.3
17            5.1          3.5           1.4          0.3
..            ...          ...           ...          ...
107           7.3          2.9           6.3          1.8
115           6.4          3.2           5.3          2.3
129           7.2          3.0           5.8          1.6
65            6.7          3.1           4.4          1.4
12            4.8          3.0           1.4          0.1
19            5.1          3.8           1.5          0.3
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
136           6.3          3.4           5.6          2.4
75            6.6          3.0           4.4          1.4
128           6.4          2.8           5.6          2.1
34            4.9          3.1           1.5          0.1
37            4.9          3.1           1.5          0.1
76            6.8          2.8           4.8          1.4
50            7.0          3.2           4.7          1.4
127           6.1          3.0           4.9          1.8
80            5.5          2.4           3.8          1.1
69            5.6          2.5           3.9          1.1
112           6.8          3.0           5.5          2.1
120           6.9          3.2           5.7          2.3
118           7.7          2.6           6.9          2.3
26            5.0          3.4           1.6          0.4
124           6.7          3.3           5.7          2.1
30            4.8          3.1           1.6          0.2
23            5.1          3.3           1.7          0.5
143           6.8          3.2           5.9          2.3
116           6.5          3.0           5.5          1.8
53            5.5          2.3           4.0          1.3
38            4.4          3.0           1.3          0.2
47            4.6          3.2           1.4          0.2

[120 rows x 4 columns]

In [111]:
def polynomial_kernel(): 
    svclassifier = SVC(kernel='poly', degree=8)  
    svclassifier.fit(X_train, y_train) 
    y_pred = svclassifier.predict(X_test)  
    
    print(confusion_matrix(y_test,y_pred))  
    
    print(classification_report(y_test,y_pred))  

In [112]:
def gaussian_kernel(): 
    svclassifier = SVC(kernel='sigmoid')  
    svclassifier.fit(X_train, y_train)  
    y_pred = svclassifier.predict(X_test)  
    print(confusion_matrix(y_test,y_pred))  
    print(classification_report(y_test,y_pred))  

In [113]:
def sigmoid_kernel():
    svclassifier = SVC(kernel='rbf')  
    svclassifier.fit(X_train, y_train)  
    y_pred = svclassifier.predict(X_test)  
    print(confusion_matrix(y_test,y_pred))  
    print(classification_report(y_test,y_pred))  

In [114]:
def test():
    polynomial_kernel()
    gaussian_kernel()
    sigmoid_kernel()

In [115]:
test()

[[ 9  0  0]
 [ 0 12  1]
 [ 0  0  8]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         9
Iris-versicolor       1.00      0.92      0.96        13
 Iris-virginica       0.89      1.00      0.94         8

      micro avg       0.97      0.97      0.97        30
      macro avg       0.96      0.97      0.97        30
   weighted avg       0.97      0.97      0.97        30

[[ 0  0  9]
 [ 0  0 13]
 [ 0  0  8]]
                 precision    recall  f1-score   support

    Iris-setosa       0.00      0.00      0.00         9
Iris-versicolor       0.00      0.00      0.00        13
 Iris-virginica       0.27      1.00      0.42         8

      micro avg       0.27      0.27      0.27        30
      macro avg       0.09      0.33      0.14        30
   weighted avg       0.07      0.27      0.11        30

[[ 9  0  0]
 [ 0 13  0]
 [ 0  0  8]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00 

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/Library/Frameworks/Python.fram